In [2]:
import numpy as np

def initialize_centroids(X, k):
    indices = np.random.choice(len(X), k, replace = False)
    return X[indices]

def assign_clusters(X, centroids):
    clusters = []
    for pt in X:
        distances = [np.linalg.norm(pt-c) for c in centroids]
        cluster_index = np.argmin(distances)
        clusters.append(cluster_index)
    return np.array(clusters)

def update_centroids(X, clusters, k):
    new_centroids = []
    for i in range(k):
        points = X[clusters==i]
        if len(points)==0:
            new_centroids.append(X[np.random.randint(0, len(X))])
        else:
            new_centroids.append(np.mean(points, axis=0))
    return np.array(new_centroids)

def kmeans(X, k, max_iters=100):
    centroids = initialize_centroids(X,k)
    for _ in range(max_iters):
        clusters = assign_clusters(X, centroids)
        new_centroids = update_centroids(X, clusters, k)
        if np.all(centroids == new_centroids):
            break

        centroids = new_centroids
    return centroids, clusters

if __name__=='__main__':
    X = np.array([
        [1, 2],
        [2, 3],
        [8, 9],
        [9, 10]
    ])
    k = 2
    centroids, clusters = kmeans(X,k)

    print("Centroids:\n", centroids)
    print("Cluster assignments:\n", clusters)



    

Centroids:
 [[1.5 2.5]
 [8.5 9.5]]
Cluster assignments:
 [0 0 1 1]


In [ ]:
import numpy as np
from sklearn.cluster import KMeans

X = np.array([
    [1, 2],
    [2, 3],
    [8, 9],
    [9, 10]
])

kmeans = KMeans(n_clusters=2, random_state=42)
kmeans.fit(X)
centroids = kmeans.cluster_centers_
labels = kmeans.labels_

print("Centroids:\n", centroids)
print("Cluster assignments:\n", labels)


Centroids:
 [[1.5 2.5]
 [8.5 9.5]]
Cluster assignments:
 [0 0 1 1]
